import type { AgentReadyConfig, ContentEntry } from "./types";

/**
 * Generate AGENTS.md — the standard file that agents (Cursor, Claude Code,
 * Copilot, etc.) look for at the repo root or served over HTTP to understand
 * the codebase.
 *
 * Our AGENTS.md is oriented at *reading* agents (web crawlers), not coding
 * agents — it tells ChatGPT/Perplexity/Claude how to best consume the site.
 */
export function generateAgentsMd(config: AgentReadyConfig, entries: ContentEntry[]): string {
  const baseUrl = config.baseUrl.replace(/\/$/, "");
  const lines: string[] = [];

  lines.push(`# AGENTS.md — ${config.name}`, "");
  lines.push(
    "This file tells AI agents (ChatGPT, Claude, Perplexity, Cursor, Copilot, etc.) how to consume this site efficiently.",
    "",
  );

  lines.push("## About", "", config.description, "");

  lines.push("## Preferred data format", "");
  lines.push(
    "Every page has a clean Markdown version. Request with `Accept: text/markdown` or append `.md` to the URL:",
    "",
    "```",
    `curl -H "Accept: text/markdown" ${baseUrl}/`,
    `curl ${baseUrl}/about.md`,
    "```",
    "",
    `Token-efficient index of all content: [${baseUrl}/llms.txt](${baseUrl}/llms.txt)`,
    "",
  );

  if (config.setup && (config.setup.install || config.setup.dev || config.setup.build)) {
    lines.push("## Running locally", "", "```bash");
    if (config.setup.install) lines.push(config.setup.install);
    if (config.setup.dev) lines.push(config.setup.dev);
    if (config.setup.build) lines.push(config.setup.build);
    lines.push("```", "");
  }

  if (entries.length) {
    lines.push("## Content map", "");
    const byLen = entries.reduce((acc, e) => acc + e.tokenEstimate, 0);
    lines.push(`${entries.length} pages, ~${byLen.toLocaleString()} tokens total.`, "");

    const bySection = new Map<string, ContentEntry[]>();
    for (const e of entries) {
      const k = e.section || "_root";
      if (!bySection.has(k)) bySection.set(k, []);
      bySection.get(k)!.push(e);
    }

    for (const [section, items] of bySection) {
      const title = config.sections?.[section] ?? (section === "_root" ? "Top level" : section);
      lines.push(`### ${title}`, "");
      for (const e of items) lines.push(`- [${e.title}](${baseUrl}${e.path === "/" ? "" : e.path})`);
      lines.push("");
    }
  }

  if (config.agentHints?.length) {
    lines.push("## Instructions for agents", "");
    for (const hint of config.agentHints) lines.push(`- ${hint}`);
    lines.push("");
  }

  lines.push("## About this file", "");
  lines.push(
    "Generated by [@agentready/next](https://agentready.tools). To update, edit `agentready.config.ts` and add content in `content/`.",
    "",
  );

  return lines.join("\n").trimEnd() + "\n";
}
